name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
